"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

format = """
$username\
$hostname\
[](fg:color_orange bg:color_yellow)\
$directory\
[](fg:color_yellow bg:color_cyan)\
$git_branch\
$git_status\
[](fg:color_cyan bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg2)\
$docker_context\
$conda\
[](fg:color_bg2 bg:color_bg1)\
$time\
[ ](fg:color_bg1 bg:color_bg1)\
$line_break\
$character"""

palette = 'cyberdream'

[palettes.cyberdream]
color_fg1 = "#3c4048"
color_fg2 = "#ffffff"
color_bg1 = "#16181a"
color_bg2 = "#3c4048"
color_bg3 = "#83a598"
color_red = "#ff6e5e"
color_orange = "#ffb35e"
color_yellow = "#f1ff5e"
color_green = "#5eff6c"
color_cyan = "#5ef1ff"
color_blue = "#5ea1ff"
color_purple = "#bd5eff"

[os]
disabled = true
style = "bg:color_orange fg:color_fg1"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg1"
style_root = "bg:color_orange fg:color_fg1"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_cyan"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_cyan)]($style)'

[git_status]
style = "bg:color_cyan"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_cyan)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol( $context) ](fg:color_bg3 bg:color_bg2)]($style)'

[conda]
style = "bg:color_bg2"
format = '[[ $symbol( $environment) ](fg:color_bg3 bg:color_bg2)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg2 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
